[tox]
skip_missing_interpreters=True

[testenv]
commands=
    pytest -p no:logging --asyncio-mode=auto --cov=alchemical --cov-branch --cov-report=term-missing --cov-report=xml tests
    pytest -p no:logging --asyncio-mode=auto examples/flaskr/tests
deps=
    greenlet
    aiosqlite
    alembic
    flask
    flask-login
    pytest
    pytest-cov
    pytest-asyncio

[testenv:pypy3]
deps=
    greenlet
    aiosqlite
    alembic
    flask
    pytest
    pytest-cov
    pytest-asyncio
commands=
    pytest -p no:logging --asyncio-mode=auto

[testenv:flake8]
deps=
    flake8
commands=
    flake8 --exclude=".*" --exclude=migrations src/alchemical tests examples

[testenv:docs]
changedir=docs
deps=
    sphinx
allowlist_externals=
    make
commands=
    make html
